### ISSUE TITLE
建议增加“标签组自由排序”功能，及其他小建议

### ISSUE THREAD

**Issue by FlyChicken233** [hy4101/OneTabPro#10]
作者大大你好！我十分喜欢这款扩展，希望越做越好✨，别人提过的建议就不重复提啦～
如题，希望标签组可通过拖拽、或上下箭头的方式自由排序，这样在用久了的场景下也更方便了。

另外，在第二次使用发现，被浏览器检测为“来源不明的扩展”自动停用了（360极速浏览器），虽然可以再次安装crx文件恢复，但仍有些不便；
这里猜测可能是没有在扩展中添加“开发者网站”信息所致，建议补充上，并可考虑上架360扩展中心https://ext.chrome.360.cn/csex_web/index.html
进一步的曝光也能增加潜在用户量，让更多人受益。😋

已关注公众号&打赏，再次感谢！

**Comment by hy4101** [comment]
非常感谢，已收到你的建议，会尽快更新，最近一直在忙公司的事，没办法打工人时间比较少

**Comment by hy4101** [comment]
相关功能在开发中了，本人测试了一轮，没什么大问题，这几天我在测试一轮，会尽快上线
![QQ截图20230611232611](https://github.com/hy4101/OneTabPro/assets/17286180/3ebb223d-355d-4ac0-a421-322628529e9f)

**Comment by hy4101** [comment]
功能已实现
![QQ截图20230617225812](https://github.com/hy4101/OneTabPro/assets/17286180/d5815376-691e-45a6-8d2a-12f08b94a62a)
