### ISSUE TITLE
昨晚升级了下 mac 的版本到13.4， 今天再打开 edge 我的标签全没了。。。

### ISSUE THREAD

**Issue by qigemingzizenmezhemekunnan** [hy4101/OneTabPro#13]
![image](https://github.com/hy4101/OneTabPro/assets/120469218/b4e70143-c827-48c8-98fd-6fce2c11b3f2)
有个报错 ：

![image](https://github.com/hy4101/OneTabPro/assets/120469218/46611627-a1c3-4788-95d9-897554ccdb05)

收起标签和新增都还可以点， 但是左侧都没有list 出现

如果没法修复我想问下 mac 下 edge 的这个拓展保存的内容在哪 我想找回我之前收藏的标签

**Comment by hy4101** [comment]
给你带来不好的体验，非常抱歉，你可以加我微信，我看看能不能给你找回来，我的我微信：miniits
