### ISSUE TITLE
注册登录时, 就算点取消操作, 所有的数据也都丢失了

### ISSUE THREAD

**Issue by JasonWong97** [hy4101/OneTabPro#16]
<img width="696" alt="image" src="https://github.com/hy4101/OneTabPro/assets/37258941/2201cae3-5c95-42bb-9f54-3ff2a92722f4">
<img width="398" alt="image" src="https://github.com/hy4101/OneTabPro/assets/37258941/0ecc0379-d943-49d3-ae42-2a2c54cd735b">

**Comment by hy4101** [comment]
可以提供版本号吗？然后能否相对详细一点的描述是如何操作的，目前我这边是没有重现出来，点取消是不会清楚本地缓存的数据

**Comment by JasonWong97** [comment]
> 
Version1.1.5
我是第一次登录时, 我不确定是因为点取消操作, 还是因为点注册, 然后登录. 
保存的一大堆网页记录都没了

**Comment by JasonWong97** [comment]
<img width="878" alt="image" src="https://github.com/hy4101/OneTabPro/assets/37258941/c9efd187-78a1-41b3-979e-5332026a7f66">
确定和取消位置是不是写反了, 异常处理的时候为什么调用login or registered 

然后刚才我再看了下, 数据又被清除了, 还是准备用回edge官方的collections了

**Comment by hy4101** [comment]
抱歉给你带来了不好的体验，我这边查的话确实没有出现你这个问题。点击事件的调用也是没有错的哦，
后期我会一直关注这个问题的，看是否会出现。
![屏幕截图 2023-07-05 214205](https://github.com/hy4101/OneTabPro/assets/17286180/b20e62d8-288b-43c0-aca5-b8389bdd32a1)
