### ISSUE TITLE
Chrome商店被下架了？

### ISSUE THREAD

**Issue by SilentLocust** [hy4101/OneTabPro#18]
从One Tab转投过来的 觉得很不错
1.1.6出现了“Https”的问题 于是一路找到这里看到更新了1.1.7插件 很高兴
但点开Chrome商店发现404？
然后直接下载Zip安装又报错说清单文件缺失……
抓狂ing
求解决之道……感谢感谢！

**Comment by hy4101** [comment]
没有哦，就是为了修复你说的那个问题，所以吧1.1.6版本给暂停发布了，以免影响更多人，1.1.7正在审核中，

**Comment by hy4101** [comment]
![屏幕截图 2023-07-09 092039](https://github.com/hy4101/OneTabPro/assets/17286180/8b9df84e-06ee-454a-9343-8ae02a55e9fc)
今天不出意外应该会审核通过，抱歉了，给你带来了不好体验啊

**Comment by SilentLocust** [comment]
> ![屏幕截图 2023-07-09 092039](https://user-images.githubusercontent.com/17286180/252121040-8b9df84e-06ee-454a-9343-8ae02a55e9fc.png) 今天不出意外应该会审核通过，抱歉了，给你带来了不好体验啊

好的好的 非常感谢 坐等更新！！

**Comment by SilentLocust** [comment]
> ![屏幕截图 2023-07-09 092039](https://user-images.githubusercontent.com/17286180/252121040-8b9df84e-06ee-454a-9343-8ae02a55e9fc.png) 今天不出意外应该会审核通过，抱歉了，给你带来了不好体验啊

好的好的 非常感谢 坐等更新！！

**Comment by SilentLocust** [comment]
> 没有哦，就是为了修复你说的那个问题，所以吧1.1.6版本给暂停发布了，以免影响更多人，1.1.7正在审核中，

感谢大神及时回复 坚定了我继续使用这个插件的决心！正好借这个楼提两个小建议供参考：

1. 界面上有导出的功能，但一直没有发现“导入”功能在哪儿
2. 能够增加一个“是否后台标签打开”的设置，因为目前默认的是点开自动跳转标签，但这样就得再点回原来的页面打开第二个。多了一道工序

【或者是上面的问题其实都已经解决了但我没发现在哪儿设置？】

请不吝赐教！

**Comment by hy4101** [comment]
![屏幕截图 2023-07-09 105721](https://github.com/hy4101/OneTabPro/assets/17286180/c408389d-22b4-4ae9-8f41-7b2eb9c6736a)
1，导入功能在设置窗口里面。
2，关于后台打开的功能，我想想怎么交互比较方便，我后期迭代时添加上去
