### ISSUE TITLE
功能建议：不将已固定的标签页发送到 OneTab Pro

### ISSUE THREAD

**Issue by macoswk** [hy4101/OneTabPro#29]
<img width="369" alt="截屏2024-03-09 13 50 32" src="https://github.com/hy4101/OneTabPro/assets/86730293/397eeaa8-90f0-45cc-adb6-75c0db04de47">

参考keptab

https://chromewebstore.google.com/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi

**Comment by hy4101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我会尽快回复你的          谢谢        王琼

**Comment by macoswk** [comment]
<img width="699" alt="截屏2024-03-09 13 58 02" src="https://github.com/hy4101/OneTabPro/assets/86730293/2ee389a7-7dde-4268-be20-b8e79e8d89d3">
onetab 也有

**Comment by macoswk** [comment]
不好意思 没看清楚 哈哈哈
