### ISSUE TITLE
所有标签页丢失

### ISSUE THREAD

**Issue by sunlj6** [hy4101/OneTabPro#30]
早上开机，打开谷歌浏览器，发现所有标签页丢失：
![image](https://github.com/hy4101/OneTabPro/assets/37824263/393aa107-26c6-41e8-99ba-4e541f5bbcdb)

**Comment by hy4101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我会尽快回复你的          谢谢        王琼

**Comment by YLRK** [comment]
+1

**Comment by hy4101** [comment]
OK了

**Comment by sunlj6** [comment]
@hy4101 可以了，多谢。

**Comment by sunlj6** [comment]
您好，所有标签页又丢失了。
![image](https://github.com/hy4101/OneTabPro/assets/37824263/65b3057a-9ac4-475e-bb08-c6139b24be1d)

**Comment by sunlj6** [comment]
@hy4101

**Comment by hy4101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我会尽快回复你的          谢谢        王琼
