### ISSUE TITLE
所有标签页再次丢失

### ISSUE THREAD

**Issue by sunlj6** [hy4101/OneTabPro#31]
- 从昨天下午开始所有标签页丢失，目前未恢复。
![image](https://github.com/hy4101/OneTabPro/assets/37824263/125b799d-5c3b-4ab8-99cb-f6cf11c34ef4)

**Comment by 1210718010** [comment]
它这个是完全依赖于云端的吗，找了半天本地啥都没存，感觉可以优化一下

**Comment by sunlj6** [comment]
@1210718010 这就不清楚了。看来从 onetab 到 onetabpro，都存在数据丢失风险，准备寻找更优的解决方案。

**Comment by Wchino** [comment]
同，不会丢了吧。。。。

**Comment by Fred0429** [comment]
目前我也是显示空白，新的标签存不进去，以前的标签找不到，不确定是否丢失

**Comment by sunlj6** [comment]
> 后才找到这个工具，还有什么替代方案吗？求推

看这篇文档， https://www.yuque.com/danmo-straw/zyko7d/rx4wk28swt4pvgmy，之前整理的，基本涵盖了大部分此类型插件。

**Comment by ddcatgg** [comment]
> 它这个是完全依赖于云端的吗，找了半天本地啥都没存，感觉可以优化一下

F12 -> 应用程序 -> 本地存储

这是 js 所能访问的除了 cookie 以外的浏览器存储空间。
能看到 OneTabPro 的标签组数据保存在 chrome-extension://fnicjegeeahadhedheialkjmmmmmgfnc 下，理论上登录成功后应该从云端下载同步，不知道为什么近期这个功能失效了。

**Comment by yinzhidong** [comment]
所有数据都丢失了，看了插件调用服务端的接口，目前都有报错

**Comment by youngsteryuan** [comment]
修好了吗

**Comment by hy4101** [comment]
非常抱歉，已经修复，等待V1.1.8版本，非常遗憾的声明，后期不会依赖云端，可能也不在提供云端服务端的功能，但是不影响使用，（这是开源项目，我有自己的工作，有时间会不定期的完善，也希望大家产于进来一起完善）

**Comment by Wchino** [comment]
已经修复了？我的还是没有。。。
