### ISSUE TITLE
有个使用上的建议

### ISSUE THREAD

**Issue by 834116404** [hy4101/OneTabPro#6]
就是收纳标签的时候 能不能不要收纳锁定状态的标签,  我浏览器是 vivaldi

**Comment by 834116404** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/36099756/235428944-6a74bd5a-6498-4672-b1c1-f90fb22bf824.png">

**Comment by hy4101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我会尽快回复你的          谢谢        王琼

**Comment by hy4101** [comment]
感谢提建议，在1.1.2版本已经新增改功能，支持设置是否收起固定之后的标签
![QQ截图20230505112523](https://user-images.githubusercontent.com/17286180/236372523-c48c4839-e181-4757-b5a9-e58b23642a0c.png)

**Comment by 834116404** [comment]
啥时候出1.1.2版本 ? 我看Chrome还是 1.1.1

**Comment by 834116404** [comment]
https://chrome.google.com/webstore/detail/pkiknjbagbmlmbdgcacgfojgplcojihf

**Comment by hy4101** [comment]
审核通过后就是1.1.2了，Chrome预计2天左右，Edge预计7天

**Comment by hy4101** [comment]
如何可以还请在Chrome商店中给个5星好评啊
