### ISSUE TITLE
能出个标签组合并功能么?

### ISSUE THREAD

**Issue by 834116404** [hy4101/OneTabPro#7]
能出个标签组合并功能么?

**Comment by 834116404** [comment]
多个标签组里面的标签合并成一个标签组,

**Comment by 834116404** [comment]
还有标签去重功能,一个标签组里面的 重复的标签去重

**Comment by hy4101** [comment]
ok、马上安排，关于合并分组有什么好的（交互上）实现方式吗？

**Comment by 834116404** [comment]
我感觉就是 来个 多选, 将多个标签合并到一个标签.

**Comment by 834116404** [comment]
再来个默认将网页收集到哪个标签的设置

**Comment by hy4101** [comment]
最后这一条就不是很明白了

**Comment by 834116404** [comment]
再来个默认将网页收集到哪个标签的设置
 这个意思就是默认将标签页收集到哪个标签组
![image](https://github.com/hy4101/OneTabPro/assets/36099756/ef36080c-e5ee-458d-83ad-4c01b5185186)

**Comment by 834116404** [comment]
其实还有一个功能点就是,  点击打开标签的时候,是否删除标签组里面的标签

**Comment by hy4101** [comment]
打开标签后删除标签，这个功能有的哦
![QQ截图20230516184802](https://github.com/hy4101/OneTabPro/assets/17286180/0154e5dd-5a82-4fa7-92fe-63c3ed5af141)

**Comment by hy4101** [comment]
去重功能已经上了哦，chrome最新版本1.1.3
![QQ截图20230517080738](https://github.com/hy4101/OneTabPro/assets/17286180/888821ff-3565-4f86-a0b3-448fc58dddea)

**Comment by hy4101** [comment]
功能已实现
![微信截图_20230613115812](https://github.com/hy4101/OneTabPro/assets/17286180/c59f6d69-1f99-4ea5-b3af-825c29465c64)
![微信截图_20230613115908](https://github.com/hy4101/OneTabPro/assets/17286180/294d4ef8-a96e-49e9-a0f9-56b9bf45b24e)
