### ISSUE TITLE
希望提供设置选项，点击图标直接收起标签页

### ISSUE THREAD

**Issue by arpir** [hy4101/OneTabPro#8]
希望提供设置选项，可以点击图标直接收起标签页，而不是现在默认的点击进去拓展详情再去点击【收起标签页按钮】。另外希望适配一下移动端，现在的布局是写死的，移动端的情况下无法自适应。我在用移动端的狐猴浏览器完美支持桌面拓展，但是现在很多拓展历史比较久的话还是写的固定布局，但是也有很多拓展是自适应的布局，比如Tampermonkey、Floccus这些，可以完美的适应移动端使用。

**Comment by hy4101** [comment]
好的最近有时间会一起给它更新上去，
大概的实现方式就是会在设置的窗口上添加一个开启或者关闭的切换按钮。
![QQ截图20230515093221](https://github.com/hy4101/OneTabPro/assets/17286180/18120767-2806-416b-a602-f6feba63833f)

**Comment by arpir** [comment]
另外希望能够适配一哈移动端，页面的布局能够随着屏幕尺寸的改变而自适应

**Comment by hy4101** [comment]
明白，移动端的会单独放一个版本去上，还要评估，工作量上比较大，也可能单独开发一个移动端的插件

**Comment by arpir** [comment]
> 明白，移动端的会单独放一个版本去上，还要评估，工作量上比较大，也可能单独开发一个移动端的插件

感觉不用啊，改哈布局就可以了我看其他的插件也没有特别去做一个移动版本，你可以看看tampermonkey这些，用狐猴浏览器用上看看

**Comment by hy4101** [comment]
是，最好是一个

**Comment by hy4101** [comment]
点击图标是否收起的功能已经上了哦
![QQ截图20230517080629](https://github.com/hy4101/OneTabPro/assets/17286180/7cf6a3fe-a640-438d-a300-9054d8480d97)

**Comment by arpir** [comment]
> 点击图标是否收起的功能已经上了哦 ![QQ截图20230517080629](https://user-images.githubusercontent.com/17286180/238798119-7cf6a3fe-a640-438d-a300-9054d8480d97.png)

OK,很快呀

**Comment by hy4101** [comment]
感谢，那能把商店的评论改为五星吗？
