### ISSUE TITLE
2个建议

### ISSUE THREAD

**Issue by Cyiming** [hy4101/OneTabPro#9]
1、建议增加onetab的仅发送此标签页、发送右侧标签页、发送左侧标签页……功能

2、建议能导入onetab的标签页 有很多人是从onetab中过来的 一部分人还是因为onetab崩溃放弃使用 如果能导入Chrome\User Data\Default\Local Storage\leveldb目录中的文件 将争取到大量用户 减少迁移成本

**Comment by hy4101** [comment]
好的，建议收到，会尽快抽时间去完善的。

**Comment by hy4101** [comment]
相关功能在开发中了，本人测试了一轮，没什么大问题，这几天我在测试一轮，会尽快上线
![QQ截图20230611232611](https://github.com/hy4101/OneTabPro/assets/17286180/e6132211-daf4-4263-9a01-e330c8660cf7)

**Comment by hy4101** [comment]
功能已实现
![Uploading QQ截图20230617225633.png…]()
